project: 
  type: website
  output-dir: _sites

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Ba Khuong Cao 's Portfolio"
        href: index.html
      - section: "Basics"
        href: Descriptive statistics.html
      - section: "Other 2"
        href: _site/Day 2.html
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: advanced.qmd
        contents:
          - raw-code.qmd
          - custom-theme.qmd
      - acknowledgment.qmd